# Generated by Django 6.0.7 on 2026-07-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('kra_pin', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField()),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/logo/')),
                ('principal_name', models.CharField(max_length=150)),
                ('deputy_principal', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
